- src/assets/scss/_global.scss
- src/components/PasswordToggle.vue
- src/modules/accounts/views/ViewLogin.vue
Added eye-icon and its functionality on the password field, 
please review once.
> PTTB-14 #comment Added eye-icon and its functionality on password field

- src/modules/tracker/components/TrackerList.vue
Project name is displayed in place of project id.
> PTTB-21 Project name is now displayed

- src/modules/tracker/components/TrackerList.vue
Added Billable/Non-billable icon instead of text and added show text while hove on each icon.
> PTTB-49 Added Billable/Non-billable icon instead of text

- src/modules/projects/components/ProjectList.vue
Removed color list from project list table aswell.
> PTTB-45 #messege removed color list from project list table

- src/modules/teams/components/RegisterUserList.vue
- src/modules/teams/services/index.js
I have added functionality on action field of registered member list in teams.
> PTTB-105 Action field functionality of registered members list

- .env.example
> PTTB-106 removed value of VITE_BACKEND_URL

- src/modules/teams/components/InviteMemberList.vue
- src/modules/teams/services/index.js
- src/modules/tracker/components/TrackerAdd.vue
- src/modules/tracker/components/TrackerList.vue
Few fixes along with revoke functionality.
> Pttb 99 revoke functionality of newly invited member

- .env.example
- src/modules/accounts/views/ViewSignup.vue
> PTTB-132 password visiblity changed

- src/modules/teams/components/InviteMember.vue
- src/modules/teams/components/InviteMemberList.vue
location reload is now removed.
> PTTB-133 Reload button is now replaced.

- src/modules/projects/components/ProjectList.vue
- src/modules/projects/services/index.js
- src/modules/tracker/components/TrackerList.vue
paginated the page and it will change to next page
> PTTB-47 paginated the page

- src/modules/teams/components/InviteMember.vue
cleared input field when clicked close button on Model
> PTTB-150 on click cancel input field gets empty

- src/modules/tracker/components/TrackerAdd.vue
Billable icon is now made billable by default.
> PTTB-16(PTTB-162-frontend-activity-logs-should-be-billable-by-default

- src/modules/teams/components/RegisterUserList.vue
Role column is now added to user list.
> PTTB-172 Role of the user is now shown in user list.

- src/modules/teams/components/RegisterUserList.vue
Now admin user can't be disabled and deleted.
> PTTB-152 Delete and disable option removed for admin user from frontend.

- src/modules/projects/components/ProjectList.vue
- src/modules/tracker/components/TrackerAdd.vue
- src/modules/tracker/components/TrackerList.vue
Gramatical corrections has been made in toast message as per discussed.Thank you!
> PTTB-164 Gramatical corrections has been made.

- src/constants/routes/projects.js
- src/modules/projects/components/ProjectList.vue
- src/modules/projects/services/index.js
Project status is now changeable.
> PTTB-167 Projects status is now editable.

- src/components/PasswordToggle.vue
- src/modules/accounts/views/ViewPasswordReset.vue
added eye icon in forget password feild
> PTTB-161 #messege eye icon added in forget password section

- src/modules/tracker/components/TrackerList.vue
displaying two toast is now fixed
> PTTB-163 two toast notofication on pressing enter is now fixed

- src/components/AddMemberDialogBox.vue
- src/components/ConfirmDelete.vue
- src/modules/projects/components/ProjectList.vue
- src/modules/projects/components/ProjectOpen.vue
- src/modules/projects/views/ViewProjects.vue
UI designed for opening project.
> PTTB-181 UI for opening project

- src/modules/projects/components/ProjectList.vue
- src/modules/tracker/components/TrackerAdd.vue
- src/modules/tracker/utils/getRealDate.js
- src/utils/getDate.js
- src/utils/getTime.js
> PTTB-190 Add tracker now working after backend changed date and time

- src/modules/tracker/components/TrackerList.vue
- src/modules/tracker/utils/getRealDate.js
- src/modules/tracker/utils/getTotalTime.js
- src/modules/tracker/utils/sortTimeLog.js
> PTTB-195 Bugs Fixed

- src/modules/clients/components/AddClient.vue
- src/modules/clients/components/ClientList.vue
- src/modules/projects/components/ProjectAdd.vue
- src/modules/projects/components/ProjectList.vue
- src/modules/tracker/components/TrackerAdd.vue
styling of pages and add tracker issue is resolved
> Pttb 194 frontend fixed the styling of all the section in proshore time tracker

- src/modules/clients/components/AddClient.vue
- src/modules/clients/components/ClientList.vue
- src/modules/clients/views/ViewClients.vue
- src/modules/projects/components/ProjectAdd.vue
- src/modules/projects/components/ProjectList.vue
- src/modules/projects/views/ViewProjects.vue
- src/modules/tracker/components/TrackerAdd.vue
- src/modules/tracker/components/TrackerList.vue
- src/modules/tracker/views/ViewTracker.vue
> Pttb 198 frontend tracker and project section must not reload while adding project

- src/modules/projects/components/ProjectAdd.vue
- src/modules/projects/components/ProjectList.vue
- src/modules/tracker/components/TrackerList.vue
> PTTB-199 minor css changes only
